find_library(ZSTD_LIBRARY NAMES zstd HINTS /usr/local/lib)
find_path(ZSTD_INCLUDE_DIR zstd.h HINTS /usr/local/include)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(ZSTD DEFAULT_MSG ZSTD_LIBRARY ZSTD_INCLUDE_DIR)
set(ZSTD_LIBRARIES ${ZSTD_LIBRARY})
set(ZSTD_INCLUDE_DIRS ${ZSTD_INCLUDE_DIR})
mark_as_advanced(ZSTD_LIBRARY ZSTD_INCLUDE_DIR)
